import { useEffect, useMemo, useState } from "react";

import { Link } from "react-router-dom";

import ReactMarkdown from "react-markdown";

import {
  ArrowRight,
  BrainCircuit,
  Clock3,
  ShieldCheck,
  Sparkles,
  TrendingUp,
} from "lucide-react";

import { getImportLogs } from "../../../api/monitoring";

export default function AiInsights() {
  const [insights, setInsights] = useState([]);

  const [loading, setLoading] = useState(true);

  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadInsights() {
      try {
        const response = await getImportLogs();

        const filteredInsights = response.logs.data.filter((item) =>
          [
            "Market Snapshot",
            "Market Conditions",
            "Market Events",
            "ETF Watchlist",
          ].includes(item.import_type_name),
        );

        setInsights(filteredInsights);
      } catch (err) {
        setError("Failed to load AI insights.");
      } finally {
        setLoading(false);
      }
    }

    loadInsights();
  }, []);

  const successfulInsights = useMemo(() => {
    return insights.filter((item) => item.status_name === "COMPLETED").length;
  }, [insights]);

  return (
    <div className="space-y-8">
      {/* Hero */}

      <section className="glass-card relative overflow-hidden rounded-3xl p-10">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,0.12),transparent_40%)]" />

        <div className="relative z-10">
          <div className="flex items-center gap-4">
            <div className="flex h-16 w-16 items-center justify-center rounded-3xl bg-cyan-500/10 text-cyan-300 shadow-glow">
              <BrainCircuit className="h-8 w-8" />
            </div>

            <div>
              <p className="font-mono text-xs uppercase tracking-[0.35em] text-cyan-300">
                ETF Rocket Intelligence Engine
              </p>

              <h1 className="mt-2 font-display text-5xl font-black text-white">
                AI Insights
              </h1>
            </div>
          </div>

          <p className="mt-8 max-w-5xl text-lg leading-relaxed text-slate-300">
            Explore AI-generated market intelligence, macroeconomic conditions,
            momentum analysis, volatility signals, and market event telemetry
            generated by ETF Rocket’s AI infrastructure.
          </p>
        </div>
      </section>

      {/* Stats */}

      <section className="grid gap-6 lg:grid-cols-3">
        <InsightCard
          icon={Sparkles}
          label="AI Insights Generated"
          value={insights.length}
          color="text-cyan-300"
        />

        <InsightCard
          icon={ShieldCheck}
          label="Successful Generations"
          value={successfulInsights}
          color="text-emerald-300"
        />

        <InsightCard
          icon={TrendingUp}
          label="Market Intelligence Engine"
          value="ACTIVE"
          color="text-violet-300"
        />
      </section>

      {/* Feed */}

      <section className="space-y-6">
        <div className="flex items-center gap-3">
          <BrainCircuit className="h-6 w-6 text-cyan-300" />

          <h2 className="font-display text-3xl font-bold text-white">
            Latest AI Intelligence
          </h2>
        </div>

        {loading ? (
          <div className="glass-card rounded-3xl p-8 text-slate-300">
            Loading AI insights...
          </div>
        ) : error ? (
          <div className="glass-card rounded-3xl p-8 text-red-400">{error}</div>
        ) : insights.length === 0 ? (
          <div className="glass-card rounded-3xl p-8 text-slate-400">
            No AI insights available yet.
          </div>
        ) : (
          insights.map((item) => (
            <div
              key={item.id}
              className="glass-card rounded-3xl p-8 transition hover:border-cyan-400/20"
            >
              <div className="flex flex-col gap-6 xl:flex-row xl:items-start xl:justify-between">
                <div>
                  <div className="flex items-center gap-3">
                    <span
                      className={`rounded-full px-4 py-1 text-xs font-semibold uppercase tracking-[0.2em] ${
                        item.status_name === "COMPLETED"
                          ? "border border-emerald-400/20 bg-emerald-400/10 text-emerald-300"
                          : "border border-amber-400/20 bg-amber-400/10 text-amber-300"
                      }`}
                    >
                      {item.status_name}
                    </span>

                    <div className="flex items-center gap-2 text-sm text-slate-400">
                      <Clock3 className="h-4 w-4" />

                      {formatDate(item.started_at)}
                    </div>
                  </div>

                  <h3 className="mt-5 font-display text-3xl font-bold text-white">
                    {item.import_type_name}
                  </h3>

                  <div className="mt-6 prose prose-invert max-w-none prose-headings:text-white prose-p:text-slate-300 prose-strong:text-cyan-300 prose-li:text-slate-300">
                    <ReactMarkdown>
                      {item.generated_markdown ||
                        "No generated content available."}
                    </ReactMarkdown>
                  </div>
                </div>

                <div className="flex-shrink-0">
                  <Link
                    to={`/dashboard/signals/report/${item.id}`}
                    className="flex items-center gap-2 rounded-2xl border border-cyan-400/20 bg-cyan-400/10 px-5 py-3 text-sm font-semibold text-cyan-300 transition hover:bg-cyan-400/20"
                  >
                    View Full Report
                    <ArrowRight className="h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
          ))
        )}
      </section>
    </div>
  );
}

function InsightCard({
  icon: Icon,

  label,

  value,

  color,
}) {
  return (
    <div className="glass-card rounded-3xl p-6">
      <div className="flex items-center justify-between">
        <div>
          <p className="font-mono text-xs uppercase tracking-[0.3em] text-slate-400">
            {label}
          </p>

          <p className={`mt-4 font-display text-4xl font-black ${color}`}>
            {value}
          </p>
        </div>

        <div className="flex h-14 w-14 items-center justify-center rounded-3xl bg-white/5">
          <Icon className={`h-6 w-6 ${color}`} />
        </div>
      </div>
    </div>
  );
}

function formatDate(value) {
  return new Date(value).toLocaleString();
}
